#!/bin/sh 

if [ -z "$1" ]; then
	echo "Usage: syncto path1 path2 ... - node ..."
	echo "       syncto path1 path2 ... @ file"
	exit 1
fi

paths=()
nodes=()

while [ ! -z "$1" ]; do
	case $1 in
		-)	shift
			nodes=$@
			break
			;;
		@)	nodes=`cat $2`
			break
			;;
		*)	paths+=($1)
			;;
	esac
	shift
done

echo "syncing from:" ${paths[@]}
echo "          to:" $nodes

for path in ${paths[@]}; do
	for node in $nodes; do
	    echo syncing $path to ${node}:`pwd`
	    rsync -a $path $node:`pwd` &
	done
done

wait
